# https://aka.ms/yaml

name: $(BuildID)

trigger:
- master

variables:
  JavaSdkDirectory: $(JAVA_HOME_8_X64)

jobs:
- job: windows
  pool:
    name: Hosted Windows 2019 with VS2019
    demands:
    - msbuild
  steps:
  - powershell: |
      ./build.ps1 -t AppVeyor
    displayName: build
  - task: PublishPipelineArtifact@0
    displayName: artifacts
    inputs:
      artifactName: artifacts
      targetPath: bin
    condition: succeededOrFailed()
