# https://aka.ms/yaml

name: $(BuildID)

trigger:
- main

jobs:
- job: windows
  pool:
    vmImage: windows-latest
    demands:
    - msbuild
  steps:
  - powershell: |
      dotnet tool restore
      dotnet cake --target=CI
    displayName: build
  - task: PublishPipelineArtifact@0
    displayName: artifacts
    inputs:
      artifactName: artifacts
      targetPath: build
    condition: succeededOrFailed()
