# https://aka.ms/yaml

name: $(BuildID)

trigger:
- master

jobs:
- job: windows
  pool:
    vmImage: windows-latest
    demands:
    - msbuild
  steps:
  - powershell: .\build.ps1 -t CI
    displayName: build
  - task: PublishPipelineArtifact@0
    displayName: artifacts
    inputs:
      artifactName: artifacts
      targetPath: build
    condition: succeededOrFailed()
